Vmc\VisitBundle\Entity\Visit:
 type: entity
 table: visit
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  patient_id:
   type: integer
  date:
   type: date
  keluhan:
   type: text
  pemeriksaan_fisik:
   type: text
  diagnosis:
   type: text
  tindakan:
   type: text
  obat:
   type: text
  biaya:
   type: string
  is_delete:
   type: boolean
